# Generated by Django 4.1.7 on 2023-12-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('aboutImage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('admission_open', models.DateTimeField()),
                ('admission_close', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name_ban', models.CharField(max_length=70, verbose_name='Student name:')),
                ('student_name_eng', models.CharField(max_length=70, verbose_name='')),
                ('father_or_hus_name_ban', models.CharField(max_length=70, verbose_name='Father/Husband name:')),
                ('father_or_hus_name_eng', models.CharField(max_length=70, verbose_name='')),
                ('village_ban', models.CharField(max_length=50, verbose_name='Village:')),
                ('village_eng', models.CharField(max_length=50, verbose_name='')),
                ('post_office_ban', models.CharField(max_length=50, verbose_name='Post office:')),
                ('post_office_eng', models.CharField(max_length=50, verbose_name='')),
                ('upozila_ban', models.CharField(max_length=50, verbose_name='Upazilla:')),
                ('upozila_eng', models.CharField(max_length=50, verbose_name='')),
                ('district_ban', models.CharField(max_length=50, verbose_name='District:')),
                ('district_eng', models.CharField(max_length=50, verbose_name='')),
                ('religion', models.CharField(choices=[('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], default='ISLAM', max_length=10, verbose_name='Religion:')),
                ('nid', models.CharField(max_length=30, verbose_name='National ID no.:')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile number:')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality:')),
                ('blood_group', models.CharField(max_length=20, verbose_name='Blood group:')),
                ('marrietal_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('UNMARRIED', 'UNMARRIED')], max_length=50, verbose_name='Marrital status:')),
                ('age', models.CharField(max_length=50, verbose_name='Age:')),
                ('edu_qualification', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'HONOURS'), ('MASTERS', 'MASTERS')], max_length=10, verbose_name='Educational qualification:')),
                ('is_pharmacy_have', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, verbose_name='Have any Pharmacy:')),
                ('pharmacy_name_address', models.CharField(max_length=200, verbose_name='Pharmacy name and address:')),
                ('past_training_name', models.CharField(max_length=100, verbose_name='Have any training:')),
                ('student_image', models.ImageField(upload_to='student_pic')),
                ('admission_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=255)),
                ('course_code', models.IntegerField(null=True)),
                ('course_credit', models.IntegerField(null=True)),
                ('course_image', models.ImageField(upload_to='pics')),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('institute_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_details', models.TextField(max_length=255)),
                ('notice_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_details', models.TextField()),
                ('teacher_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAgent', models.CharField(max_length=15)),
                ('taxInId', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('studentInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.studentinfo')),
            ],
        ),
    ]
