# Generated by Django 4.1.7 on 2024-01-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4000)),
                ('aboutImage', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('circular', models.ImageField(upload_to='circulars')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_details', models.TextField()),
                ('member_pic', models.ImageField(upload_to='committee_pics')),
                ('member_voice', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=255)),
                ('course_code', models.IntegerField(null=True)),
                ('course_credit', models.IntegerField(null=True)),
                ('course_image', models.ImageField(upload_to='pics')),
                ('description', models.TextField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('institute_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('regi_number', models.CharField(max_length=255, null=True)),
                ('mono_regi_number', models.CharField(max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
                ('event_date', models.DateField(null=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_details', models.TextField(max_length=255)),
                ('notice_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=40)),
                ('agent_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_details', models.TextField()),
                ('teacher_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('village', models.CharField(max_length=255, null=True)),
                ('post_office', models.CharField(max_length=255, null=True)),
                ('upozilla', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('nid', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('student_pic', models.ImageField(upload_to='student_pic')),
                ('edu_qualification', models.CharField(max_length=255, null=True)),
                ('edu_cirtificate', models.ImageField(upload_to='cirtificate')),
                ('pharmacy', models.BooleanField(null=True)),
                ('pharmacy_address', models.CharField(max_length=255, null=True)),
                ('payment_amount', models.IntegerField(default=0, null=True)),
                ('taxInId', models.CharField(max_length=30, null=True)),
                ('admission_date', models.DateField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('membership_number', models.CharField(max_length=255, null=True)),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.course')),
                ('payment_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_agents', to='courses.paymentagent')),
                ('total_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='courses.cost')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_amount', models.IntegerField(default=0)),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.studentinfo')),
                ('total_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.cost')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_image', to='courses.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_name', to='courses.teacher'),
        ),
        migrations.AddField(
            model_name='cost',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_open', models.DateTimeField()),
                ('admission_close', models.DateTimeField()),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_notice', to='courses.course')),
            ],
        ),
    ]
