# Generated by Django 4.1.7 on 2024-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
