# Generated by Django 4.1.7 on 2023-12-18 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='district_ban',
            field=models.CharField(max_length=50, verbose_name='District:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='district_eng',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='father_or_hus_name_ban',
            field=models.CharField(max_length=70, verbose_name='Father/Husband name:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='father_or_hus_name_eng',
            field=models.CharField(max_length=70, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nationality:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='nid',
            field=models.CharField(max_length=30, verbose_name='National ID no.:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='pharmacy_name_address',
            field=models.CharField(max_length=200, verbose_name='Pharmacy name and address:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_office_ban',
            field=models.CharField(max_length=50, verbose_name='Post office:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='post_office_eng',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='student_name_ban',
            field=models.CharField(max_length=70, verbose_name='Student name:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='student_name_eng',
            field=models.CharField(max_length=70, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='upozila_ban',
            field=models.CharField(max_length=50, verbose_name='Upazilla:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='upozila_eng',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='village_ban',
            field=models.CharField(max_length=50, verbose_name='Village:'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='village_eng',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
