# Generated by Django 4.1.6 on 2023-12-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer_image',
            field=models.ImageField(null=True, upload_to='trainer_pics'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=4000),
        ),
    ]
