# Generated by Django 4.1.5 on 2023-03-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(null=True),
        ),
    ]
