# Generated by Django 4.1.7 on 2024-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='membership_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
