# Generated by Django 4.1.7 on 2024-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentinfo_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_details', models.TextField(verbose_name=255)),
                ('member_pic', models.ImageField(upload_to='committee_pics')),
            ],
        ),
    ]
