# Generated by Django 4.1.6 on 2023-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description_course_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer_image',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
