# Generated by Django 4.1.6 on 2023-12-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_admissionform_admission_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RmpLmf',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='admission_link',
        ),
    ]
