# Generated by Django 4.1.6 on 2023-12-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_trainer_image_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('admission_open', models.DateTimeField()),
                ('admission_close', models.DateTimeField()),
                ('student_name_ban', models.CharField(max_length=70, verbose_name='Student name:')),
                ('student_name_eng', models.CharField(max_length=70, verbose_name='')),
                ('father_or_hus_name_ban', models.CharField(max_length=70, verbose_name='Father/Husband name:')),
                ('father_or_hus_name_eng', models.CharField(max_length=70, verbose_name='')),
                ('village_ban', models.CharField(max_length=50, verbose_name='Village:')),
                ('village_eng', models.CharField(max_length=50, verbose_name='')),
                ('post_office_ban', models.CharField(max_length=50, verbose_name='Post office:')),
                ('post_office_eng', models.CharField(max_length=50, verbose_name='')),
                ('upozila_ban', models.CharField(max_length=50, verbose_name='Upazilla:')),
                ('upozila_eng', models.CharField(max_length=50, verbose_name='')),
                ('district_ban', models.CharField(max_length=50, verbose_name='District:')),
                ('district_eng', models.CharField(max_length=50, verbose_name='')),
                ('religion', models.CharField(choices=[('ISLAM', 'ISLAM'), ('OTHERS', 'OTHERS')], default='ISLAM', max_length=10, verbose_name='Religion:')),
                ('nid', models.CharField(max_length=30, verbose_name='National ID no.:')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile number:')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality:')),
                ('blood_group', models.CharField(max_length=20, verbose_name='Blood group:')),
                ('marrietal_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('UNMARRIED', 'UNMARRIED')], max_length=50, verbose_name='Marrital status:')),
                ('age', models.CharField(max_length=50, verbose_name='Age:')),
                ('edu_qualification', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'HONOURS'), ('MASTERS', 'MASTERS')], max_length=10, verbose_name='Educational qualification:')),
                ('is_pharmacy_have', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, verbose_name='Have any Pharmacy:')),
                ('pharmacy_name_address', models.CharField(max_length=200, verbose_name='Pharmacy name and address:')),
                ('past_training_name', models.CharField(max_length=100, verbose_name='Have any training:')),
                ('student_image', models.ImageField(upload_to='student_pic')),
                ('admission_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='AdmissionForm',
        ),
    ]
