# Generated by Django 4.1.7 on 2024-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='member_voice',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member_details',
            field=models.TextField(),
        ),
    ]
