# Generated by Django 4.1.7 on 2024-01-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_login_sign_up'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_up',
            new_name='Signup',
        ),
    ]
