# Generated by Django 4.1.6 on 2023-12-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_admissionnotice_delete_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionnotice',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='age',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='district_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='district_eng',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='edu_qualification',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='father_or_hus_name_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='father_or_hus_name_eng',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='is_pharmacy_have',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='marrietal_status',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='past_training_name',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='pharmacy_name_address',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='post_office_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='post_office_eng',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='student_image',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='student_name_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='student_name_eng',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='upozila_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='upozila_eng',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='village_ban',
        ),
        migrations.RemoveField(
            model_name='admissionnotice',
            name='village_eng',
        ),
    ]
