# Generated by Django 4.1.7 on 2023-12-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentinfo_alter_admissionform_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAgent', models.CharField(max_length=15)),
                ('taxInId', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('studentInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.studentinfo')),
            ],
        ),
    ]
