# Generated by Django 4.1.7 on 2024-01-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_sign_up_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='name',
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=1, max_length=55),
        ),
    ]
