# Generated by Django 4.1.6 on 2023-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_admissionnotice_admission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('circular', models.ImageField(upload_to='circulars')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
    ]
