# Generated by Django 4.1.7 on 2023-12-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_paymentadmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentadmission',
            old_name='studentInfo',
            new_name='student_id',
        ),
    ]
