# Generated by Django 5.0.1 on 2024-01-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_signup_name_signup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
