# Generated by Django 4.1.5 on 2023-04-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='details',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
