# Generated by Django 4.1.7 on 2023-12-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_circular'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_image', to='courses.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_name', to='courses.teacher'),
        ),
    ]
