# Generated by Django 4.1.7 on 2023-12-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_teacher_image_course_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentadmission',
            old_name='studentInfo',
            new_name='name',
        ),
    ]
