# Generated by Django 4.1.7 on 2023-12-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_paymentadmission_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('details', models.CharField(max_length=255)),
            ],
        ),
    ]
