# Generated by Django 4.1.7 on 2023-12-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_studentinfo_paymentadmission_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentadmission',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='paymentadmission',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.studentinfo'),
        ),
    ]
