# Generated by Django 5.0.1 on 2024-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_custom_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='membership_number',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
