# Generated by Django 4.1.5 on 2023-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
