# Generated by Django 4.1.7 on 2023-12-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_paymentadmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='payment_agent',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='taxInId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paymentadmission',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.studentinfo'),
        ),
    ]
