# Generated by Django 4.1.7 on 2023-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_studentinfo_date_studentinfo_payment_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=40)),
                ('agent_number', models.CharField(max_length=11)),
            ],
        ),
    ]
