# Generated by Django 4.1.7 on 2023-12-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_paymentagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='payment_agent',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='agent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_agent', to='courses.paymentagent'),
        ),
    ]
