# Generated by Django 4.1.6 on 2023-05-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_details',
        ),
    ]
