# Generated by Django 4.1.6 on 2023-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_teacher_teacher_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_details',
            field=models.TextField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_details',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
