# Generated by Django 4.1.5 on 2023-05-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_notice_notice_details_teacher_teacher_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
