# Generated by Django 4.1.5 on 2023-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_notice_notice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('admission_open', models.DateTimeField()),
                ('admission_close', models.DateTimeField()),
                ('admission_link', models.URLField(verbose_name='')),
            ],
        ),
    ]
