# Generated by Django 4.1.5 on 2023-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('edu_qualification', models.CharField(max_length=255)),
            ],
        ),
    ]
