# Generated by Django 4.1.5 on 2023-05-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_admissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='date_of_birth',
        ),
    ]
