# Generated by Django 4.1.6 on 2023-12-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_admissionform_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('institute_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=50)),
            ],
        ),
    ]
